name: "TB7 Saldo Checker"
description: "Addon for checking saldo at tb7.pl"
version: "1.0.2"
slug: "tb7_saldo_checker"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
hassio_api: true
options:
  username: ""
  password: ""
schema:
  username: str
  password: str