name: "PGNiG Saldo Checker"
description: "Addon for checking saldo at PGNiG eBOK"
version: "1.0.0"
slug: "pgnig_saldo_checker"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
homeassistant_api: true
options:
  username: ""
  password: ""
schema:
  username: str
  password: str