name: "Moico Saldo Checker"
description: "Addon for checking saldo at Moico eBOK"
version: "1.0.7"
slug: "moico_saldo_checker"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
homeassistant_api: true
hassio_api: true
options:
  username: ""
  password: ""
schema:
  username: str
  password: str