name: "Ikea Strandmon Checker"
description: "Addon for checking Strandmon price at Ikea"
version: "1.0.19"
slug: "ikea_strandmon_checker"
init: false
legacy: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
homeassistant_api: true
