name: "SM Piast Saldo Checker"
description: "Addon for checking saldo at SM Piast eBOK"
version: "1.0.3"
slug: "smpiast_saldo_checker"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
homeassistant_api: true
options:
  username: ""
  password: ""
schema:
  username: str
  password: str