name: "Tauron Saldo Checker"
description: "Addon for checking saldo at Tauron eBOK"
version: "1.0.5"
slug: "tauron_saldo_checker"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
homeassistant_api: true
options:
  username: ""
  password: ""
schema:
  username: str
  password: str